name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0"
    - uses: actions/checkout@v4
    - name: Run tests
      run: swift test
