name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        swift_version:
          - "5.10"
          - "6.0"
    runs-on: macos-latest
    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift_version }}
    - uses: actions/checkout@v4
    - name: Run tests
      run: swift test
